#!/usr/bin/env python3
"""Generate src/components/screens/agents.ts from the app's own source.

The landing page draws a recreation of the Home pane rather than a screenshot,
so the type stays vector. That only works if the recreation cannot drift from
the app, which is what this script is for: the colours come from
AgentPalette.swift and the logo paths from AgentLogos.swift, so a palette change
in the app is one command away from being a site change too.

    python3 tools/sync-site-agents.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGOS = os.path.join(ROOT, "mac/AgentSpend/UI/AgentLogos.swift")
PALETTE = os.path.join(ROOT, "mac/AgentSpend/UI/AgentPalette.swift")
OUT = os.path.join(ROOT, "src/components/screens/agents.ts")

# The agents the marketing screen shows. Deliberately a subset: the tile is
# ~330px wide and a six-agent legend wraps into two lines, which reads as
# clutter rather than as capability.
SHOWN = ["claude-code", "codex", "gemini", "copilot"]


def main():
    logos = dict(re.findall(r'"([a-z-]+)": "([^"]+)"', open(LOGOS).read()))
    pal = open(PALETTE).read()
    colors = {
        a: "#%02x%02x%02x" % tuple(round(float(v) * 255) for v in (r, g, b))
        for a, r, g, b in re.findall(
            r'"([a-z-]+)":\s*Color\(red:\s*([\d.]+),\s*green:\s*([\d.]+),\s*blue:\s*([\d.]+)\)',
            pal)
    }
    labels = dict(re.findall(r'case "([a-z-]+)":\s*return "([^"]+)"', pal))

    lines = [
        "// Generated by tools/sync-site-agents.py from the app's own",
        "// AgentPalette.swift and AgentLogos.swift. Do not edit by hand: the point",
        "// is that the site cannot drift from what the app actually draws.",
        "",
        "export type Agent = {",
        "  key: string;",
        "  label: string;",
        "  color: string;",
        "  /** 24x24 path, or null where no vendor publishes a usable mark. */",
        "  path: string | null;",
        "};",
        "",
        "export const AGENTS: Agent[] = [",
    ]
    for a in SHOWN:
        if a not in colors:
            raise SystemExit(f"{a} has no colour in AgentPalette.swift")
        d = logos.get(a)
        path = f'"{d}"' if d else "null"
        lines.append(f'  {{ key: "{a}", label: "{labels.get(a, a)}", '
                     f'color: "{colors[a]}", path: {path} }},')
    lines += ["];", ""]
    open(OUT, "w").write("\n".join(lines))
    print(f"wrote {OUT}")
    for a in SHOWN:
        print(f"  {a:14} {colors[a]}  {'logo' if logos.get(a) else 'lettermark'}")


if __name__ == "__main__":
    main()
